server:
  port: 8080
  servlet:
    context-path: /v1/concurrence-control

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  config:
    activate:
      on-profile: local
  datasource:
    url: "jdbc:postgresql://localhost:5433/bank"
    username: "postgres"
    password: "12345678"
    driver: "org.postgresql.Driver"
    hikari:
      maximum-pool-size: 10
  jpa:
    defer-datasource-initialization: true
  sql:
    init:
      mode: "always"