server:
  port: 8080

spring:
  config:
    activate:
      on-profile: develop
  webflux:
    base-path: /concurrence-control/v1
  datasource:
    url: "jdbc:mysql://localhost:3306/bank?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSl=false"
    username: "root"
    password: "12345678"
  jpa:
    database-platform: "org.hibernate.dialect.MySQLDialect"