server:
  port: 8080

spring:
  config:
    activate:
      on-profile: develop
  webflux:
    base-path: /concurrence-control/v1
  datasource:
    url: "jdbc:postgresql://db_postgres:5432/bank"
    username: "postgres"
    password: "12345678"
  jpa:
    database-platform: "org.hibernate.dialect.PostgreSQLDialect"